### ISSUE TITLE
PagingCollectionViewController<T: Products> issue

### ISSUE THREAD

**Issue by DidarSeyidov** [BreakZero/EasyWallet-KMP#38]
```
func startLoadProductss() {
    Task {
        try? await asyncSequence(for: getProducts()).collect { pagingData in
              try? await delegate.submitData(pagingData: pagingData)
            
        }
    }
}
```
I thing there is a problem on above function, it returns always empty [ ] list,
and when I set input data type to Any on PagingCollectionViewController<T: Any>, swiftUI cannot recognize Any type,
please help

**Comment by BreakZero** [comment]
Hi @DidarSeyidov for empty list, could you check what the result you get from `getProducts`?

**Comment by DidarSeyidov** [comment]
Flow<PaginData<Products>>

**Comment by BreakZero** [comment]
Yes, you can log the result to check if the flow emit the empty list. 
For `Any` data type, you can see more [here](https://github.com/cashapp/multiplatform-paging/blob/main-3.3.0-alpha02/paging-runtime-uikit/src/iosMain/kotlin/app/cash/paging/PagingCollectionViewController.kt#L18)

**Comment by DidarSeyidov** [comment]
suspend fun submitData(pagingData: PagingData<T>) {
        differ.submitData(pagingData)
    }
Is @NativeCoroutines missed on this function?
